name: Node.js CI

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npx hardhat test
  
  coverage:
    runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npx hardhat coverage